# Generated by Django 3.2.16 on 2023-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
